services:
  - type: web
    name: takuma-landing
    runtime: ruby
    plan: starter
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: SECRET_KEY_BASE
        generateValue: true
